version: '3'

services:
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    container_name: api
    env_file:
      - .env
#    depends_on:
#      - kafka
#    networks:
#      - kafka-network
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: app
        target: /go/src/app

  db:
    build:
      context: .
      dockerfile: build/db/Dockerfile
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
#    networks:
#      - kafka-network
    volumes:
      - type: volume
        source: db-data8
        target: /var/lib/mysql
        volume:
          nocopy: true

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#    networks:
#      - kafka-network

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    ports:
#      - "9092:9092"
#    hostname: kafka
#    depends_on:
#      - zookeeper
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - container_name=kafka
#    networks:
#      - kafka-network

#networks:
#  kafka-network:
#    driver: bridge

volumes:
  db-data8:
